version: "3"

volumes:
  satu-password-postgresdb-data:
    name: satu-password-postgresdb-data
  satu-password-jenkins-data:
    name: satu-password-jenkins-data

networks:
  satu-password-network:
    name: satu-password-network
    driver: bridge

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    volumes:
      - satu-password-postgresdb-data:/var/lib/postgresql/data
    env_file:
      - ./secrets/postgresdb/.env
    ports:
      - 5432:5432
    networks:
      - satu-password-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 443:443
    networks:
      - satu-password-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf

      - ./secrets/nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./secrets/nginx/privkey.pem:/etc/nginx/certs/privkey.pem

      - ./secrets/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
    links:
      - jenkins
    depends_on:
      - jenkins

  webapp:
    container_name: webapp
    build:
      context: ./webapp/
      dockerfile: Dockerfile
    image: "webapp:latest"
    ports:
      - 3000:3000
    depends_on:
      - postgresdb
    links:
      - postgresdb
    networks:
      - satu-password-network

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins/
      dockerfile: Dockerfile
    image: "jenkins:latest"
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - satu-password-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - satu-password-jenkins-data:/var/jenkins_home
